fix(djs-utilities): fixed parameter types for type guards
sapphiredev/utilities pull request #152
Opened 2021-08-11 17:22 UTC by Favna

After merging this PR all of these usages are valid usages:

![](https://sapphire.actually-needs-more.tech/56Q6JgeTv)

We completely dropped the ball on this tbh because the current parameters
straight up don't allow checking for a channel that comes directly from the cache.

2021-08-11 17:23 UTC, vladfrangu approved these changes

2021-08-11 17:41 UTC, kyranet commented
Why not `channel?.type === ...`?

2021-08-11 19:01 UTC, Favna commented
Changed it to optional chaining @kyranet

2021-08-12 18:21 UTC, kyranet requested changes

2021-08-12 18:55 UTC, kyranet approved these changes

2021-08-12 18:58 UTC, vladfrangu approved these changes

2021-08-12 19:22 UTC, Favna commented
@sapphiredev pack

2021-08-12 19:32 UTC, merged