fix(PaginatedMessage): I couldn't take it, sorry
sapphiredev/utilities pull request #187
Opened 2021-09-30 02:17 UTC by kaname-png

2021-09-30 08:48 UTC, kyranet requested changes

2021-09-30 08:48 UTC, kyranet commented on packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
> +				embed.footer.text = `${this.pageIndexPrefix ? `${this.pageIndexPrefix} ` : ''}${index + 1} / ${this.pages.length} | ${
The idea is that the `|` is only appended when there's a footer text.
```suggestion
				embed.footer.text = `${this.pageIndexPrefix ? `${this.pageIndexPrefix} ` : ''}${index + 1} / ${this.pages.length}${
```

2021-09-30 19:23 UTC, jurienhamaker commented on packages/discord.js-utilities/src/lib/PaginatedMessages/PaginatedMessage.ts
> +					embed.footer.text ? ` | ${embed.footer.text}` : ''
Might as well make it configureable kekw

2021-09-30 21:53 UTC, Favna requested changes
I don't get it at all. Plus Kyra's comment needs to be resolved.

2021-10-01 00:49 UTC, Favna commented
Closing because this what this PR was meant to fix, was actually already fixed in a4e5a567a4d75dbba57df6774664ebaff55c24f4

2021-10-01 00:49 UTC, closed without merging