feat(discord-utilities): add discord limits
sapphiredev/utilities pull request #224
Opened 2021-11-27 17:05 UTC by noftaly

Add different limits related to discord.

I have intentionnally missed a few ones such as the one bellow, because i wanted your opinion:
- max # of persons in a channel with a video [25]
- max # of guilds for a classic / nitro user (why would a bot need that?) [100 / 200 i think]
- max # of members in a guild (if you reach max you can ask discord for more so this isn't a hard limit) [500k]
- other limits that can be 💥 with boosts, such as max # of emojis/stickers per guild and max upload size [50 / 0 / 8Mo, 100 / 15 / 8Mo, 150 / 30 / 50Mo, 250 / 60 / 100Mo]

2021-11-27 22:59 UTC, favna requested changes
comments go for all constants, ofc.

2021-11-27 22:59 UTC, favna commented on packages/discord-utilities/src/lib/limits.ts
> +export const ChannelLimits = {
tsdoc on the constant

2021-11-27 22:59 UTC, favna commented on packages/discord-utilities/src/lib/limits.ts
> +export const EmbedLimits = {
tsdoc on the constant

2021-11-28 11:40 UTC, favna approved these changes

2021-11-28 11:59 UTC, kyranet requested changes

2021-11-28 11:59 UTC, kyranet commented on packages/discord-utilities/src/lib/limits.ts
> +};
This here and everywhere else.
```suggestion
} as const;
```

2021-11-28 13:23 UTC, favna approved these changes

2021-11-29 11:46 UTC, kyranet requested changes

2021-11-29 11:46 UTC, kyranet commented on packages/discord-utilities/src/lib/limits.ts
> +	 * Maximum viewers allowed per screen share.
?

2021-11-29 19:47 UTC, kyranet approved these changes

2021-11-29 20:07 UTC, favna approved these changes

2021-11-29 20:07 UTC, merged