fix: fixed date cloning
sapphiredev/utilities pull request #275
Opened 2022-01-27 22:34 UTC by favna

fixes #272

wew lad

2022-01-27 23:18 UTC, kyranet requested changes

2022-01-27 23:18 UTC, kyranet commented on packages/utilities/src/lib/deepClone.ts
> +		const output = new (source.constructor as DateConstructor)(source.toISOString());
```suggestion
		const output = new (source.constructor as DateConstructor)(source);
```

2022-01-27 23:30 UTC, kyranet approved these changes

2022-01-28 00:31 UTC, vladfrangu approved these changes

2022-01-28 00:39 UTC, c43721 approved these changes

2022-01-28 17:57 UTC, merged