feat(discord-utilities): Add token regex
sapphiredev/utilities pull request #302
Opened 2022-02-26 19:33 UTC by Commandtechno

A token regex can be useful for automatically resetting tokens, and validating tokens before making requests or connecting to the gateway.

Source is from searching TOKEN_REGEX in https://canary.discord.com/assets/2fa49c2711296797d83c.js

![image](https://user-images.githubusercontent.com/68407783/155856623-de9325a7-e339-4d14-9275-d1b1a4348d79.png)

2022-02-26 19:46 UTC, vladfrangu submitted a review, later dismissed

2022-02-26 20:46 UTC, favna requested changes

2022-02-26 20:46 UTC, favna commented on packages/discord-utilities/src/lib/regexes.ts
> +export const TokenRegex = /(mfa\.[a-z0-9_-]{20,})|([a-z0-9_-]{23,28}\.[a-z0-9_-]{6,7}\.[a-z0-9_-]{27})/i;
```suggestion
/**
 * Regex that can capture a Discord Token
 * @raw `/(?<mfaToken>mfa\.[a-z0-9_-]{20,})|(?<sfaToken>[a-z0-9_-]{23,28}\.[a-z0-9_-]{6,7}\.[a-z0-9_-]{27})/i`
 * @remark Capture group 1 can be used to retrieve a token for a User that has Multi-Factor Authentication enabled. It is named `mfaToken`.
 * @remark Capture group 2 can be used to retrieve a token for a Bot application, or a User that does not have Multi-Factor Authentication enabled. It is named `sfaToken`.
 * @remark For a valid token, either Capture group 1 or Capture group 2 will always be undefined, whereas the other group will then be defined and contain the matched token.
 * You can use the name of the capture group to determine if the validated token was configured for a user with Multi-Factor Authentication.
 * If both capture groups are undefined, then the token is invalid.
 */
export const TokenRegex = /(?<mfaToken>mfa\.[a-z0-9_-]{20,})|(?<sfaToken>[a-z0-9_-]{23,28}\.[a-z0-9_-]{6,7}\.[a-z0-9_-]{27})/i;
```

2022-02-26 22:21 UTC, vladfrangu commented on packages/discord-utilities/src/lib/regexes.ts
> +export const TokenRegex = /(mfa\.[a-z0-9_-]{20,})|([a-z0-9_-]{23,28}\.[a-z0-9_-]{6,7}\.[a-z0-9_-]{27})/i;
sure

2022-02-27 23:16 UTC, vladfrangu approved these changes

2022-02-27 23:16 UTC, Commandtechno commented
I changed botToken to basicToken since this regex also matches tokens for users without 2FA enabled (tested on my alt's token)

2022-02-27 23:27 UTC, favna approved these changes

2022-02-28 10:40 UTC, kyranet approved these changes

2022-02-28 18:17 UTC, merged