fix(discord-utilities) update webhook regex
sapphiredev/utilities pull request #307
Opened 2022-03-05 06:15 UTC by Commandtechno

Its been discord.com for a while, and this regex does not work for current webhooks
Also made it match API versions since those work too

![image](https://commandtechno.com/i/77pnnhu4dd8x)

2022-03-05 09:53 UTC, favna approved these changes

2022-03-05 10:31 UTC, kyranet requested changes

2022-03-05 10:31 UTC, kyranet commented on packages/discord-utilities/src/lib/regexes.ts
> +export const WebhookRegex = /(?<url>^https:\/\/(?:(?:canary|ptb).)?discord(app)?.com\/api(\/v\d+)?\/webhooks\/(?<id>\d+)\/(?<token>[\w-]+)\/?$)/;
Make them non-capturing groups
```suggestion
export const WebhookRegex = /(?<url>^https:\/\/(?:(?:canary|ptb).)?discord(?:app)?.com\/api(?:\/v\d+)?\/webhooks\/(?<id>\d+)\/(?<token>[\w-]+)\/?$)/;
```

2022-03-06 20:19 UTC, favna approved these changes

2022-03-07 19:02 UTC, kyranet approved these changes

2022-03-07 19:55 UTC, merged