fix(PaginatedMessages): missing logic cases
sapphiredev/utilities pull request #331
Opened 2022-04-20 02:09 UTC by Mzato0001

Fixes #330

2022-04-20 11:08 UTC, vladfrangu submitted a review, later dismissed

2022-04-21 06:49 UTC, favna approved these changes

2022-04-21 06:54 UTC, favna requested changes

2022-04-21 06:54 UTC, favna commented on packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
> +		action.type === "SELECT_MENU" ||
```suggestion
		action.type === 'SELECT_MENU' ||
```

2022-04-21 06:54 UTC, favna commented on packages/discord.js-utilities/src/lib/PaginatedMessages/utils.ts
> +	return interaction.type === Constants.MessageComponentTypes.BUTTON || interaction.type === "BUTTON";
```suggestion
	return interaction.type === Constants.MessageComponentTypes.BUTTON || interaction.type === 'BUTTON';
```

2022-04-21 06:54 UTC, favna approved these changes

2022-04-21 09:49 UTC, kyranet approved these changes

2022-04-21 21:54 UTC, merged

2022-04-21 22:01 UTC, favna commented
Released in v4.9.5