feat: accept JS objects for request body
sapphiredev/utilities pull request #365
Opened 2022-05-28 19:26 UTC by enxg

2022-05-28 19:27 UTC, vladfrangu requested changes

2022-05-28 19:27 UTC, vladfrangu commented on packages/fetch/src/lib/fetch.ts
> +interface RequestOptions extends Omit<RequestInit, 'body'> {
Should be exported

2022-05-28 19:32 UTC, vladfrangu submitted a review, later dismissed

2022-06-04 15:43 UTC, favna requested changes

2022-06-04 15:43 UTC, favna commented on packages/fetch/src/lib/fetch.ts
> +import { FetchResultTypes, RequestOptions } from './types';
```suggestion
import { FetchResultTypes, type RequestOptions } from './types';
```

2022-06-04 15:43 UTC, favna commented on packages/fetch/src/lib/fetch.ts
> +	if (typeof body === 'object' && body !== null) {
Resolved without code change @enxg

2022-06-04 15:54 UTC, favna approved these changes

2022-06-05 17:05 UTC, vladfrangu approved these changes

2022-06-05 17:06 UTC, merged