feat: add `@sapphire/lexure` package
sapphiredev/utilities pull request #388
Opened 2022-07-02 19:24 UTC by kyranet

## TODO

- Tests
- Docs

2022-07-02 22:04 UTC, c43721 commented
omg omg omg omg

I can write the docs at a later point (more like help with docs)

2022-07-09 07:44 UTC, vladfrangu commented on packages/lexure/src/lib/lexer/streams/raw/TokenStream.ts
> +export const enum TokenType {
If this is exported to end users, dont make it const

2022-07-09 12:56 UTC, UndiedGamer commented on packages/lexure/src/lib/parser/Parser.ts
> +	public constructor(strategy: IUnorderedStrategy) {
```suggestion
	public constructor(strategy?: IUnorderedStrategy) {
```
This is to make the next line valid

2022-07-09 20:04 UTC, favna commented
PR still has TODOs so converted to draft

2022-07-13 21:07 UTC, favna requested changes

2022-07-13 21:07 UTC, favna commented on packages/lexure/package.json
> +	}
```suggestion
	"devDependencies": {
		"@favware/cliff-jumper": "^1.8.5",
		"tsup": "^6.1.3",
		"typescript": "^4.7.4"
	}
```

2022-07-17 07:40 UTC, UndiedGamer requested changes

2022-07-17 07:40 UTC, UndiedGamer commented on packages/lexure/src/lib/parser/Parser.ts
> +		return new ParserResult(this).parse(input);
mfw this has been in pending since 3 days

2022-07-19 15:50 UTC, UndiedGamer commented on packages/lexure/src/lib/parser/Parser.ts
> +		return new ParserResult(this).parse(input);
This was resolved in a different way

2022-07-20 00:07 UTC, c43721 submitted a review, later dismissed

2022-07-21 22:14 UTC, favna requested changes

2022-07-21 22:14 UTC, favna commented on packages/lexure/README.md
> +-   ~~Fully tested~~ WIP
```suggestion
-   Fully tested
```

Done enough for this claim

2022-07-21 22:15 UTC, favna submitted a review, later dismissed

2022-07-21 22:22 UTC, c43721 submitted a review, later dismissed

2022-07-21 22:42 UTC, vladfrangu requested changes

2022-07-21 22:42 UTC, vladfrangu commented on packages/lexure/src/lib/lexer/Lexer.ts
> +	public readonly quotes: readonly [string, string][];
```suggestion
	public readonly quotes: readonly [open: string, close: string][];
```

2022-07-21 22:42 UTC, vladfrangu commented on packages/lexure/src/lib/lexer/Lexer.ts
> +		quotes?: readonly [string, string][];
```suggestion
		quotes?: readonly [open: string, close: string][];
```

2022-07-21 22:43 UTC, vladfrangu approved these changes

2022-07-21 22:50 UTC, c43721 approved these changes

2022-07-21 22:52 UTC, favna approved these changes

2022-07-22 07:57 UTC, merged