feat: add `join` and `joinRaw`
sapphiredev/utilities pull request #458
Opened 2022-09-17 22:31 UTC by kyranet

A little utility `lexure` had that we didn't. Most useful for https://github.com/sapphiredev/framework/pull/531.

2022-09-17 22:33 UTC, vladfrangu approved these changes

2022-09-18 11:06 UTC, favna requested changes

2022-09-18 11:06 UTC, favna commented on packages/lexure/src/lib/util/util.ts
> +	}
```suggestion
	for (const parameter of parameters) {
		output += parameter.leading + parameter.raw;
	}
```

Were you half asleep or something

2022-09-18 11:06 UTC, favna commented on packages/lexure/src/lib/util/util.ts
> +	}
```suggestion
	for (const param of parameters) {
		output += param.leading + param.value;
	}
```

2022-09-18 11:06 UTC, kyranet commented on packages/lexure/src/lib/util/util.ts
> +	}
It starts from 1, not 0.

2022-09-18 11:10 UTC, favna commented on packages/lexure/src/lib/util/util.ts
> +	}
I guess I'm the one half asleep then

2022-09-18 11:10 UTC, favna approved these changes

2022-09-18 11:10 UTC, merged