feat: make @sapphire/stopwatch browser compitible
sapphiredev/utilities pull request #470
Opened 2022-09-30 18:32 UTC by imranbarbhuiya

fixes: #271

2022-09-30 21:15 UTC, favna requested changes

2022-09-30 21:15 UTC, favna commented on packages/stopwatch/src/tsconfig.json
> +		"lib": ["dom", "dom.iterable", "esnext"],
```suggestion
		"lib": ["dom", "esnext"],
```

Doesn't `dom` also include `dom.iterable`?

2022-09-30 21:15 UTC, favna commented on packages/stopwatch/tsup.config.ts
> +	}
CJS and ESM don't need imports either, `performance` is available globally in Node:

![image](https://user-images.githubusercontent.com/4019718/193356871-925f95f7-e609-4638-8dc8-b0e1f38030fe.png)

2022-09-30 21:16 UTC, favna requested changes
Also add to the top of `index.ts`:
```ts
// eslint-disable-next-line spaced-comment
/// <reference lib="dom" />
```

the added `dom` in tsconfig doesn't work for end-users

2022-10-01 09:20 UTC, kyranet submitted a review, later dismissed

2022-10-01 13:00 UTC, vladfrangu submitted a review, later dismissed

2022-10-01 14:27 UTC, favna requested changes

2022-10-01 14:27 UTC, favna commented on packages/stopwatch/tsup.config.ts
> +	globalName: 'Stopwatch'
```suggestion
	globalName: 'SapphireStopwatch'
```

`Sapphire` prefix to retain consistency

2022-10-01 14:48 UTC, favna approved these changes

2022-10-01 14:49 UTC, merged