feat(utilities): add `objectEntries` function
sapphiredev/utilities pull request #471
Opened 2022-09-30 18:55 UTC by RealShadowNova

Resolves #455

2022-09-30 21:45 UTC, kyranet requested changes

2022-09-30 21:45 UTC, kyranet commented on packages/utilities/tests/objectEntries.test.ts
> +		expect(objectEntries(source)).toEqual(expected);
Same as the other PR, please assert the input type + test readonly objects.

2022-10-01 06:31 UTC, imranbarbhuiya requested changes

2022-10-01 06:31 UTC, imranbarbhuiya commented on packages/utilities/src/lib/objectEntries.ts
> +	return Object.entries(obj) as [keyof T, T[keyof T]][];
same as the other 2 prs. You can better make 2 generic typings in `utility-types` files which can give all keys type and all values type. And use that in these 3 functions

2022-10-01 14:10 UTC, RealShadowNova commented
Should I change the return type for the key to a `string` or to a template literal containing `number` in the case of an array?
![image](https://user-images.githubusercontent.com/46537907/193413498-3a79b564-25de-4801-966a-abdce7059d2b.png)

2022-10-01 14:12 UTC, favna reviewed
template literal same as the other pr

2022-10-01 14:51 UTC, favna approved these changes

2022-10-01 15:28 UTC, vladfrangu submitted a review, later dismissed

2022-10-01 15:35 UTC, favna requested changes

2022-10-01 15:35 UTC, favna commented on packages/utilities/src/lib/objectEntries.ts
> +	return Object.entries(obj) as T extends ArrayLike<any> ? [`${number}`, T[number]][] : [keyof T, T[keyof T]][];
comment on #474 is a good one

```suggestion
	return Object.entries(obj) as T extends ArrayLike<infer Values> ? Values[] : [keyof T, T[keyof T]][];
```

<img width="684" alt="image" src="https://user-images.githubusercontent.com/4019718/193416894-da1a9610-98f9-4c7a-b2c6-227989130baa.png">
<img width="722" alt="image" src="https://user-images.githubusercontent.com/4019718/193416901-06fe9e82-3310-4424-9dda-d04c01b20c20.png">

2022-10-01 16:03 UTC, merged