feat(utilities): add `objectKeys` function
sapphiredev/utilities pull request #472
Opened 2022-09-30 18:59 UTC by RealShadowNova

Resolves #457

2022-09-30 21:45 UTC, kyranet requested changes

2022-09-30 21:45 UTC, kyranet commented on packages/utilities/tests/objectKeys.test.ts
> +		expect(objectKeys(source)).toEqual(expected);
Same as the other PR, please assert the input type + test readonly objects.

2022-10-01 06:29 UTC, imranbarbhuiya requested changes

2022-10-01 06:29 UTC, imranbarbhuiya commented on packages/utilities/src/lib/objectKeys.ts
> +	return Object.keys(obj) as (keyof T)[];
```suggestion
export function objectKeys<T extends NonNullObject>(obj: T):  T extends ArrayLike<any> ? number[] : (keyof T)[] {
	return Object.keys(obj) as T extends ArrayLike<any> ? number[] : (keyof T)[]
```

2022-10-01 14:08 UTC, RealShadowNova commented
Should I change the return type to a `string` or to a template literal containing `number` in the case of an array?
![image](https://user-images.githubusercontent.com/46537907/193413386-1e486707-c304-4e5f-87e7-ba546a89647a.png)

2022-10-01 14:10 UTC, imranbarbhuiya commented
template literal containing `number`

2022-10-01 14:11 UTC, favna approved these changes

2022-10-01 14:51 UTC, favna approved these changes

2022-10-01 15:29 UTC, vladfrangu approved these changes

2022-10-01 15:37 UTC, favna requested changes

2022-10-01 15:37 UTC, favna commented on packages/utilities/src/lib/objectKeys.ts
> +	return Object.keys(obj) as T extends ArrayLike<any> ? `${number}`[] : (keyof T)[];
```suggestion
	return Object.keys(obj) as T extends ArrayLike<infer Values> ? Values[] : (keyof T)[];
```

2022-10-01 16:06 UTC, favna approved these changes

2022-10-01 16:10 UTC, merged