feat(result): add `Result.unwrapRaw`
sapphiredev/utilities pull request #475
Opened 2022-09-30 22:59 UTC by favna

This is essentially a shortcut for:
```ts
	return result.match({
		err: (error) => {
			throw error;
		},
		ok: (value) => value.data[0]
	});
```
which can then be written as:
```ts
return result.map((value) => value.data[0]).unwrapRaw();
```

This is useful when instead of throwing a `ResultError` you want to instead throw the inner error (i.e. `ArgumentError` for Sapphire, see sapphiredev/framework#528, or a `FetchError` from @skyra/safe-fetch, something that brought about this change)

2022-09-30 23:03 UTC, kyranet requested changes

2022-09-30 23:03 UTC, kyranet commented on packages/result/tests/Result.test.ts
> +				const x = err(new Error('Some error message'));
Assign the error to a variable.

2022-09-30 23:03 UTC, kyranet commented on packages/result/tests/Result.test.ts
> +				}
```suggestion
				const error = new Error('Some error message');
				const x = err(error);

				expect(() => x.unwrapRaw()).toThrowError(error);
```

2022-09-30 23:03 UTC, kyranet commented on packages/result/src/lib/Result/IResult.ts
> +	 * @seealso {@link unwrapOrElse}
The linked unwrap methods should `@seealso {@link unwrapRaw}`.

2022-10-01 00:13 UTC, kyranet approved these changes

2022-10-01 12:46 UTC, vladfrangu approved these changes

2022-10-01 14:28 UTC, merged