feat(utilities): add retry function from discord chat
sapphiredev/utilities pull request #604
Opened 2023-06-07 21:45 UTC by favna

Thanks goes to @kyranet

2023-06-07 21:46 UTC, vladfrangu submitted a review, later dismissed

2023-06-07 21:52 UTC, kyranet requested changes
I wonder if we should have a `retrySync` (or a sync `retry` with `retryAsync`). 🤔

2023-06-07 21:52 UTC, kyranet commented on packages/utilities/src/lib/retry.ts
> + * @param  retries The number of retries is also passed in as a parameter.
```suggestion
 * @param cb The function to be retried is passed in as a callback function.
 * @param retries The number of retries is also passed in as a parameter.
```

2023-06-07 21:52 UTC, kyranet commented on packages/utilities/src/lib/retry.ts
> + * The function will retry the call to the callback function until it either succeeds or it runs out of retries.
```suggestion
 * Calls the callback function until it either succeeds or it runs out of retries.
```

2023-06-07 21:52 UTC, kyranet commented on packages/utilities/tests/retry.test.ts
> +		const result = await retry(() => 'test', 3);
If we use `vi.fn`, we can test how many times the function is called to ensure the amount is correct.

2023-06-07 21:52 UTC, kyranet commented on packages/utilities/tests/retry.test.ts
> +		const cb = () => {
Ditto

2023-06-09 08:19 UTC, kyranet approved these changes

2023-06-09 08:27 UTC, vladfrangu approved these changes

2023-06-09 08:32 UTC, kyranet submitted a review, later dismissed

2023-06-09 08:33 UTC, kyranet approved these changes

2023-06-09 08:34 UTC, vladfrangu requested changes
Forgot to re-export in index.ts :megu:

2023-06-09 08:42 UTC, vladfrangu approved these changes

2023-06-09 09:15 UTC, merged